### ISSUE TITLE
Otsu Thresholding

### ISSUE THREAD

**Issue by saisiril** [MX-Futhark/text-position-detector#2]
The term 'sum' has to be i*data[i] for the whole histogram

**Comment by MX-Futhark** [comment]
You may very well be right, my mathematical background is too light to implement variants of Otsu's algorithm without dumb mistakes. I'm sure there are plenty of mistakes elsewhere, too.

Can you please explain why the current implementation is faulty?

That being said, I'm afraid I don't have enough time to maintain this project at the moment. I see you've forked the project: feel free to open a pull request that fixes the problem.

**Comment by saisiril** [comment]
Sure, will make some changes. I'm trying to implement the same algorithm in python. Came across your code while searching. Thanks.
